version: 0.2

phases:
  install:
    commands:
      - echo Entering install phase...
#      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Entering pre_build phase...
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - chmod 755 ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo Entering post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - 'demo-0.0.1-SNAPSHOT.jar'
  base-directory: 'build/libs'
  discard-paths: yes